evaluate_customer_interaction:
  description: >
    Assess the customer service agent's response in relation to the customer's query. Use the "last_answer" provided to evaluate response accuracy, clarity, and overall helpfulness. Determine if the response meets quality standards and suggest improvements if necessary.

    LAST ANSWER TO EVALUATE
    -----------------------
    {last_answer}

    CONSIDERATIONS
    --------------
    - Does it completely and accurately address the customer’s issue?
    - Is it concise, clear and easy to understand?
    - Is the tone appropriate and professional?
    - Be strict, don't approve too easily

  expected_output: >
    A JSON object with:
    - `approved` (boolean): True if the response meets quality standards, otherwise False.
    - `feedback` (string): Specific feedback on improving clarity, completeness, or tone, if needed.

  agent: evaluation_agent