customer_query:
  description: >
    My account login is not recognizing my email address. Give a solution to the customer's issue.
    If it's available, use feedback provided to refine your response and address specific points raised by the evaluator.

    LAST ANSWER
    -----------
    {last_answer}

    FEEDBACK
    --------
    {feedback}

    ADDITIONAL INSTRUCTIONS
    -----------------------
    Modify the solution based on evaluator feedback to create a more effective response. Ensure the following:
    - Any specific issues raised in feedback are resolved.
    - The solution is tailored to improve user experience.

  expected_output: >
    A clear solution to the email recognition issue that incorporates feedback. Address each feedback point explicitly and provide a rationale for adjustments made.

  agent: technical_support_agent